"""Recovery of known scaling-law parameters from synthetic data.

These are the load-bearing tests for the package: if data really are generated by a scaling law, the fitter
must find that law -- including at the small experiment sizes the package is designed for.
"""

import numpy as np
import pytest

from simple_scaling_laws import fit
from simple_scaling_laws.simulate import simulate_runs

TRUE_LOSS = {"E": 1.0, "A": 2.0, "alpha": 0.3, "B": 1.5, "beta": 0.25}


def test_noiseless_recovery_is_exact():
    """With no noise at all, the fitted parameters must reproduce the generating law."""
    frame = simulate_runs({"test_loss__ce": TRUE_LOSS}, runs_per_config=1, evaluations_per_run=1, seed=0)
    model = fit(frame, n_draws=50, seed=0)
    fitted = model.params("test_loss__ce")
    for name, truth in TRUE_LOSS.items():
        assert fitted[name] == pytest.approx(truth, abs=1e-4), name


def test_recovery_with_noise():
    """With realistic run and evaluation noise, parameters land close to the truth."""
    frame = simulate_runs(
        {"test_loss__ce": TRUE_LOSS},
        runs_per_config=2,
        evaluations_per_run=5,
        run_sd=0.02,
        eval_sd=0.03,
        seed=0,
    )
    model = fit(frame, n_draws=400, seed=0)
    fitted = model.params("test_loss__ce")
    assert fitted["alpha"] == pytest.approx(TRUE_LOSS["alpha"], abs=0.05)
    assert fitted["beta"] == pytest.approx(TRUE_LOSS["beta"], abs=0.05)
    assert fitted["E"] == pytest.approx(TRUE_LOSS["E"], abs=0.2)


def test_confidence_intervals_cover_the_truth():
    """The bootstrap intervals must contain the generating values."""
    frame = simulate_runs(
        {"test_loss__ce": TRUE_LOSS},
        runs_per_config=2,
        evaluations_per_run=5,
        run_sd=0.02,
        eval_sd=0.03,
        seed=3,
    )
    model = fit(frame, n_draws=400, seed=0)
    intervals = model.conf_int("test_loss__ce")
    for name, truth in TRUE_LOSS.items():
        low, high = intervals[name]
        assert low <= truth <= high, f"{name}: {truth} outside [{low}, {high}]"


def test_recovery_at_minimal_scale():
    """A three-by-three grid with a single run per configuration still recovers the exponents."""
    frame = simulate_runs(
        {"test_loss__ce": TRUE_LOSS},
        runs_per_config=1,
        evaluations_per_run=3,
        run_sd=0.01,
        eval_sd=0.02,
        seed=7,
    )
    model = fit(frame, n_draws=200, seed=0)
    fitted = model.params("test_loss__ce")
    assert model.manifest["n_configurations"] == 9
    assert model.manifest["n_training_runs"] == 9
    assert fitted["alpha"] == pytest.approx(TRUE_LOSS["alpha"], abs=0.08)
    assert fitted["beta"] == pytest.approx(TRUE_LOSS["beta"], abs=0.08)


@pytest.mark.parametrize("seed", range(6))
def test_recovery_is_robust_across_noise_realizations(seed):
    """Exponent recovery must not depend on a lucky random seed."""
    frame = simulate_runs(
        {"test_loss__ce": TRUE_LOSS},
        runs_per_config=2,
        evaluations_per_run=4,
        run_sd=0.02,
        eval_sd=0.03,
        seed=seed,
    )
    model = fit(frame, n_draws=100, seed=0)
    fitted = model.params("test_loss__ce")
    assert fitted["alpha"] == pytest.approx(TRUE_LOSS["alpha"], abs=0.08)
    assert fitted["beta"] == pytest.approx(TRUE_LOSS["beta"], abs=0.08)


def test_increasing_metric_recovers_negative_amplitudes():
    """A metric that improves with scale approaches its asymptote from below."""
    truth = {"E": 0.92, "A": -0.15, "alpha": 0.4, "B": -0.08, "beta": 0.3}
    frame = simulate_runs(
        {"test_metric__auroc": truth},
        runs_per_config=2,
        evaluations_per_run=5,
        run_sd=0.004,
        eval_sd=0.008,
        seed=0,
    )
    model = fit(frame, n_draws=200, seed=0)
    fitted = model.params("test_metric__auroc")
    assert fitted["A"] < 0 and fitted["B"] < 0
    assert fitted["E"] == pytest.approx(truth["E"], abs=0.03)
    assert fitted["alpha"] == pytest.approx(truth["alpha"], abs=0.15)


def test_loss_amplitudes_are_constrained_non_negative():
    """Losses use the asymptotic-floor parameterization, so amplitudes cannot go negative."""
    truth = {"E": 2.0, "A": -0.5, "alpha": 0.3, "B": -0.4, "beta": 0.25}
    frame = simulate_runs(
        {"test_loss__ce": truth}, runs_per_config=1, evaluations_per_run=2, eval_sd=0.01, seed=0
    )
    model = fit(frame, n_draws=50, seed=0)
    fitted = model.params("test_loss__ce")
    assert fitted["A"] >= 0 and fitted["B"] >= 0
    codes = {note.code for note in model.warnings}
    assert "parameter_at_bound" in codes


def test_multiplicative_law_recovery():
    """The joint-power law recovers its own generating parameters."""
    truth = {"E": 1.0, "A": 3.0, "alpha": 0.3, "beta": 0.2}
    frame = simulate_runs(
        {"test_loss__ce": truth},
        law="multiplicative-power",
        runs_per_config=2,
        evaluations_per_run=4,
        run_sd=0.01,
        eval_sd=0.02,
        seed=0,
    )
    model = fit(frame, law="multiplicative-power", n_draws=200, seed=0)
    fitted = model.params("test_loss__ce")
    for name, value in truth.items():
        assert fitted[name] == pytest.approx(value, abs=0.15), name


def test_exponents_are_invariant_to_predictor_units():
    """Rescaling a predictor's units must not change its exponent, only its amplitude."""
    frame = simulate_runs(
        {"test_loss__ce": TRUE_LOSS},
        runs_per_config=2,
        evaluations_per_run=4,
        run_sd=0.01,
        eval_sd=0.02,
        seed=0,
    )
    rescaled = frame.with_columns(model_size__n_params=frame["model_size__n_params"] * 1000.0)
    base = fit(frame, n_draws=50, seed=0).params("test_loss__ce")
    other = fit(rescaled, n_draws=50, seed=0).params("test_loss__ce")
    assert other["alpha"] == pytest.approx(base["alpha"], rel=1e-6)
    assert other["A"] == pytest.approx(base["A"], rel=1e-6)


def test_fit_uses_run_level_observations_not_evaluation_rows():
    """The curve is fit to one observation per trained model, whatever the evaluation count."""
    frame = simulate_runs(
        {"test_loss__ce": TRUE_LOSS},
        runs_per_config=2,
        evaluations_per_run=25,
        run_sd=0.02,
        eval_sd=0.05,
        seed=0,
    )
    model = fit(frame, n_draws=50, seed=0)
    goodness = model.fits["test_loss__ce"].goodness_of_fit
    assert goodness["n_observations"] == 18
    assert model.manifest["n_evaluation_rows"] == 450


def test_predictions_track_the_true_curve():
    """Predicted medians at unseen interior scales are close to the generating curve."""
    frame = simulate_runs(
        {"test_loss__ce": TRUE_LOSS},
        runs_per_config=2,
        evaluations_per_run=5,
        run_sd=0.01,
        eval_sd=0.02,
        seed=0,
    )
    model = fit(frame, n_draws=200, seed=0)
    points = {"model_size__n_params": [3e6, 3e7], "dataset_size__n_subjects": [3e3, 3e4]}
    predictions = model.predict(points)
    domain = model.observed_domain
    reference = np.array([domain[name]["reference"] for name in model.predictors])
    raw = np.column_stack([points["model_size__n_params"], points["dataset_size__n_subjects"]])
    log_x = np.log(raw) - np.log(reference)
    truth = model.law.evaluate(np.array([TRUE_LOSS[n] for n in model.law.param_names]), log_x)
    assert np.allclose(predictions["test_loss__ce__median"].to_numpy(), truth, atol=0.05)
